## Домашнее задание "Библиотека pandas"

### Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [240]:
import pandas as pd

In [241]:
movies = pd.read_csv('pandas_data/movies.dat', sep='::', engine='python', names=['MovieID', 'Name', 'Genre'])
ratings = pd.read_csv('pandas_data/ratings.dat', sep='::', engine='python', names=['UserID', 'MovieID', 'Rating', 'Timestamp'])

In [242]:
data = ratings[['MovieID', 'Rating']]
grouped_data = data[data['Rating'] == 5].groupby(['MovieID']).count().sort_values('Rating', ascending=False)
grouped_data.merge(movies, on='MovieID').head(1)

   MovieID  Rating                    Name         Genre
0     2858    1963  American Beauty (1999)  Comedy|Drama

### Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [243]:
data = pd.read_csv('pandas_data/power.csv')

Суммарно по всем категориям:

In [244]:
def baltic(country):
    if country in ['Latvia', 'Lithuania', 'Estonia']:
        return True
    return False

def suitable_category(category):
    if category in [4, 12, 21]:
        return True
    return False

def accounting_period(year):
    return 2005 <= year <= 2010

data['is_Baltic'] = data.country.apply(baltic)
data['is_suitable_cat'] = data.category.apply(suitable_category)

baltic_data = data[ data['is_Baltic'] & data['is_suitable_cat'] & (data.quantity > 0) & (data.year.apply(accounting_period)) ]
baltic_data['quantity'].sum()

240580.0

По каждой категории:

In [245]:
baltic_data.groupby('category').sum()['quantity'].to_frame()

          quantity
category
4             46.0
12          6326.0
21        234208.0

### Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.

In [246]:
mendeleev = pd.read_html('https://chemtoday.ru/mendeleev/')[0]
mendeleev.replace(to_replace=r'Все статьи', value=' ', regex=True)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
1,"1 H Водород 1,008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2 He Гелий 4,0026"
2,"3 Li Литий 6,941","4 Be Бериллий 9,0122",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5 B Бор 10,811","6 C Углерод 12,0111","7 N Азот 14,0067","8 O Кислород 15,999","9 F Фтор 18,998","10 Ne Неон 20,179"
3,"11 Na Натрий 22,989","12 Mg Магний 24,305",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"13 Al Алюминий 26,9815","14 Si Кремний 28,086","15 P Фосфор 30,973","16 S Сера 32,064","17 Cl Хлор 35,454","18 Ar Аргон 39,948"
4,"19 K Калий 39,098","20 Ca Кальций 40,08","21 Sc Скандий 44,956","22 Ti Титан 47,867","23 V Ванадий 50,942","24 Cr Хром 51,996","25 Mn Марганец 54,938","26 Fe Железо 55,845","27 Co Кобальт 58,933","28 Ni Никель 58,693","29 Cu Медь 63,546","30 Zn Цинк 65,39","31 Ga Галлий 69,723","32 Ge Германий 72,631","33 As Мышьяк 74,922","34 Se Селен 78,972","35 Br Бром 79,904","36 Kr Криптон 83,798"
5,"37 Rb Рубидий 85,468","38 Sr Стронций 87,62","39 Y Иттрий 88,906","40 Zr Цирконий 91,224","41 Nb Ниобий 92,906","42 Mo Молибден 95,95","43 Tc Технеций 98,906","44 Ru Рутений 101,07","45 Rh Родий 102,91","46 Pd Палладий 106,42","47 Ag Серебро 107,87","48 Cd Кадмий 112,41","49 In Индий 114,82","50 Sn Олово 118,71","51 Sb Сурьма 121,76","52 Te Теллур 127,60","53 I Иод 126,91","54 Xe Ксенон 131,29"
6,"55 Cs Цезий 132,91","56 Ba Барий 137,33","57 La Лантан 138,91","72 Hf Гафний 178,49","73 Ta Тантал 180,95","74 W Вольфрам 183,84","75 Re Рений 186,21","76 Os Осмий 190,23","77 Ir Иридий 192,22","78 Pt Платина 195,08","79 Au Золото 196,97","80 Hg Ртуть 200,59","81 Tl Таллий 204,38","82 Pb Свинец 207,20","83 Bi Висмут 208,98",84 Po Полоний [209],85 At Астат [210],86 Rn Радон [222]
7,87 Fr Франций [223],88 Ra Радий [226],89 Ac Актиний [227],104 Rf Резерфордий [267],105 Db Дубний [268],106 Sg Сиборгий [269],107 Bh Борий [270],108 Hs Хассий [277],109 Mt Мейтнерий [278],110 Ds Дармштадтий [281],111 Rg Рентгений [282],112 Cn Коперниций [285],113 Nh Нихоний [286],114 Fl Флеровий [289],115 Mc Московий [290],116 Lv Ливерморий [293],117 Ts Теннесин [294],118 Og Оганесон [294]
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,Лантаноиды,"58 Ce Церий 140,12","59 Pr Празеодим 140,91","60 Nd Неодим 144,24",61 Pm Прометий [145],"62 Sm Самарий 150,36","63 Eu Европий 151,96","64 Gd Гадолиний 157,25","65 Tb Тербий 158,93","66 Dy Диспрозий 162,50","67 Ho Гольмий 164,93","68 Er Эрбий 167,26",69 Tm Тулий 168.94,"70 Yb Иттербий 173,04","71 Lu Лютеций 174,97",NaN
10,NaN,NaN,Актиноиды,"90 Th Торий 232,04","91 Pa Протактиний 231,04","92 U Уран 238,029",93 Np Нептуний [237],94 Pu Плутоний [244],95 Am Америций [243],96 Cm Кюрий [247],97 Bk Берклий [247],98 Cf Калифорний [251],99 Es Эйнштейний [254],100 Fm Фермий [257],101 Md Менделевий [258],102 No Нобелий [259],103 Lr Лоуренсий [266],NaN