## Домашнее задание «Функции и работа с данными»

### Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [128]:
import pandas as pd

In [129]:
movies = pd.read_csv('pandas_data_2/movies.csv', sep=',')
ratings = pd.read_csv('pandas_data_2/ratings.csv', sep=',')

In [130]:
movies_rating = ratings.groupby('movieId').mean().reset_index()[['movieId','rating']]
movies_with_rating = movies.merge(movies_rating, on='movieId', how='left')

def classification(rating):
    if rating <= 2:
        return 'Низкий'
    elif rating <= 4:
        return 'Средний'
    elif rating > 4:
        return 'Высокий'
    else:
        return 'Без рейтинга'

movies_with_rating['class'] = movies_with_rating.rating.apply(classification)
movies_with_rating.head()

,movieId,title,genres,rating,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.872470,Средний
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.401869,Средний
2,3,Grumpier Old Men (1995),Comedy|Romance,3.161017,Средний
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.384615,Средний
4,5,Father of the Bride Part II (1995),Comedy,3.267857,Средний

## Задание 2
Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

In [131]:
keywords = pd.read_csv('pandas_data_2/keywords.csv', sep=',')

In [132]:
geo_data = {
    'Центр': ['москва', 'тула', 'ярославль'],
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [133]:
def find_region(keyword):
    for region, city_list in geo_data.items():
        for city in city_list:
            if city in keyword:
                return region
    return 'undefined'            

keywords['region'] = keywords.keyword.apply(find_region)

In [134]:
keywords.query('region in ("Центр", "Северо-Запад", "Дальний Восток")')

                                     keyword   shows          region
127                             авито москва  979292           Центр
370                 авито ру санкт петербург  425134    Северо-Запад
564                погода в санкт петербурге  292489    Северо-Запад
849                          авито ярославль  209581           Центр
1063                     фарпост владивосток  176951  Дальний Восток
...                                      ...     ...             ...
99590  авито ярославль автомобили с пробегом    3673           Центр
99634   северпост новости мурманской области    3606    Северо-Запад
99808      полармед мурманск запись на прием    3719    Северо-Запад
99890                    яндекс метро москва    4548           Центр
99922                      авто ру ярославль    3712           Центр

[747 rows x 3 columns]

## Задание 3 (бонусное)

Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия, т.е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

In [135]:
years = list(range(1950, 2011))

In [136]:
movies = pd.read_csv('pandas_data_2/movies.csv', sep=',')
ratings = pd.read_csv('pandas_data_2/ratings.csv', sep=',')

In [137]:
def production_year(title):
    for year in years:
        if str(year) in title:
            return year
    return 1900

def get_rating(movieId):
    return ratings[ratings['movieId'] == movieId].rating.mean()

movies['year'] = movies.title.apply(production_year)
movies['rating'] = movies.movieId.apply(get_rating)

movies.groupby('year').mean().sort_values('rating',ascending=False)

           movieId    rating
year
1951  12929.565217  3.906653
1952  14703.148148  3.802318
1962   9199.975610  3.772962
1953   9516.083333  3.738878
1957   9061.463415  3.693322
...            ...       ...
2002   9615.166052  3.191918
1997   4617.168539  3.183169
1990  11460.654930  3.166759
2003  12511.777311  3.154081
2001   8671.325843  3.133080

[62 rows x 2 columns]

Вывод: раньше снимали настоящее кино, не то что сейчас!